unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pane navigation with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Swap window position with ctrl+h, ctrl+l
set -g renumber-windows on
bind H swap-window -t -1
bind L swap-window -t +1

# Rename window with r
bind r command-prompt -I "#W" "rename-window '%%'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Mouse movement
set -g mouse on

# Panes
set -g pane-border-style 'fg=#908784'
set -g pane-active-border-style 'fg=white'

# Statusbar appearance
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#403939"

set -g status-left-length 50

set -g status-right-style 'fg=#908784 bg=#403939'
set -g status-right ' %Y-%m-%d %H:%M '
# set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=#908784'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=blue bg=#403939'
setw -g window-status-format ' #I #[fg=white] #W #[fg=yellow]#F '

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g extended-keys on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
